"""Your message describing the migration

Revision ID: 891995f018e8
Revises: 
Create Date: 2025-01-26 00:38:16.396042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '891995f018e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    op.drop_table('books')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_borrowed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('borrowed_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('borrowed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('book_id', name='books_pkey')
    )
    op.create_table('members',
    sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('member_id', name='members_pkey'),
    sa.UniqueConstraint('email', name='members_email_key')
    )
    # ### end Alembic commands ###
