"""Initial tables (books, members)

Revision ID: b1088644b3c4
Revises: 
Create Date: 2025-01-27 12:18:05.910419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from uuid import uuid4

# revision identifiers, used by Alembic.
revision: str = 'b1088644b3c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'books',
        sa.Column('book_id', sa.UUID(), primary_key=True, default=uuid4),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('author', sa.String(), nullable=False),
        sa.Column('is_borrowed', sa.Boolean(), default=False),
        sa.Column('borrowed_date', sa.DateTime(), nullable=True),
        sa.Column('borrowed_by', sa.UUID(), nullable=True),
    )

    # Create members table
    op.create_table(
        'members',
        sa.Column('member_id', sa.UUID(), primary_key=True, default=uuid4),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False, unique=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    op.drop_table('members')
    # ### end Alembic commands ###
