"""
Initial tables (books, members)
Revision ID: fdbe330cf61c
Revises:
Create Date: 2025-01-27 13:16:31.723529
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fdbe330cf61c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
                    sa.Column('book_id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('author', sa.String(), nullable=False),
                    sa.Column('is_borrowed', sa.Boolean(), nullable=True),
                    sa.Column('borrowed_date', sa.DateTime(), nullable=True),
                    sa.Column('borrowed_by', sa.UUID(), nullable=True),
                    sa.Column('created_by', sa.UUID(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.UUID(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('book_id')
                    )
    op.create_table('members',
                    sa.Column('member_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('created_by', sa.UUID(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.UUID(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('member_id'),
                    sa.UniqueConstraint('email')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    op.drop_table('books')
    # ### end Alembic commands ###
